### ISSUE TITLE
Truncated Cell Barcodes

### ISSUE THREAD

**Issue by ayyildizd** [broadinstitute/CellBender#200] opened 2023-04-19 09:16 UTC
Hi and thanks for developing this great tool! (looking forward to v3)

I am using Cell Bender v0.2.2 after processing SPLiT-seq samples with STAR solo. Specific to the technology I have 3x8bp barcodes separated by underscore so it is 26 characters in total and I just realised that Cellbender outputs 20bp barcodes so my barcodes comes out as truncated. This creates problem because now there are many duplications in cell barcodes. 

Thanks in advance!

**Comment by sjfleming** [comment] 2023-04-24 18:16
Ah!  We don't want that... I have to admit I am not quite sure why that is happening.

I will try to write myself up a little test case and see if I can reproduce this.  Are you using an `.h5ad` AnnData format file as input for cellbender?

**Comment by ayyildizd** [comment] 2023-04-24 18:22
I use the whole folder coming out from STAR solo. The input folder includes matrix.mtx, genes.tsv and barcodes.tsv.

**Comment by sjfleming** [comment] 2023-04-24 18:26
Okay thanks for responding.

Whoops, there it is!
https://github.com/broadinstitute/CellBender/blob/b9fd92dec1cb89ac923df19aee3cf44543d23fa6/cellbender/remove_background/data/dataset.py#L892

So I was going off the spec from CellRanger (since that is technically the format CellBender says it supports).  But I'd definitely like to make it work for STAR solo format as well.

For now, one workaround you could use would be to open your dataset with `anndata` and save a `.h5ad` file to use as input for cellbender.  I think this should work, since I do not believe there is any restriction on the size of barcodes for `.h5ad` format inputs.

I think in a future update I can probably change that line to `dtype='<U20'`, hopefully without any problems.  That should take care of any barcode size.

**Comment by sjfleming** [comment] 2023-04-24 18:27
Thank you for reporting this!

**Comment by sjfleming** [comment] 2023-08-08 20:10
Closed by #238

**Closed by sjfleming** 2023-08-08 20:10 UTC
Labels: enhancement
