### ISSUE TITLE
Failed reading 10x h5 file - CellBender v2.1

### ISSUE THREAD

**Issue by GreenGilad** [broadinstitute/CellBender#66] opened 2020-08-06 09:02 UTC
Last week I ran CellBender v1 over a CellRanger V3 library I got, and then successfully loaded the h5 output into a Seurat object.
```
CreateSeuratObject(Read10X_h5("the_cell_bender_outout_filtered.h5"))
````

Now, when I tried using CellBender V2.1 instead of V1 over the same CellRanger library, I got the following exception:
```
Error in `[[.H5File`(infile, paste0(genome, "/", feature_slot)) :
  An object with name matrix/gene_names does not exist in this group
```

Comparing the output h5 files of both versions they seem to have the same format with the difference that the V2.1 output has the `"PYTABLES_FORMAT_VERSION"`. Is it flagged like that on purpose? This is the flag that causes the Seurat Read10X_h5 function to fail: (part of Read10X_h5 code)

```
  infile <- hdf5r::H5File$new(filename = filename, mode = "r")
  genomes <- names(x = infile)
  output <- list()
  if (!infile$attr_exists("PYTABLES_FORMAT_VERSION")) {
    if (use.names) {
      feature_slot <- "features/name"
    }
    else {
      feature_slot <- "features/id"
    }
  }
  else {
    if (use.names) {
      feature_slot <- "gene_names"
    }
    else {
      feature_slot <- "genes"
    }
  }
```

**Comment by GreenGilad** [comment] 2020-08-06 11:44
A temporary workaround that seemed to solve the problem is that in the case of a CellRanger V3 (where the `matrix` group has the `features` group) to remove the `"PYTABLES_FORMAT_VERSION"` attribute using:
```
f <- hdf5r::H5File$new("file_name.h5", mode="a")
f$attr_delete("PYTABLE_FORMAT_VERSION")
f$close_all()
```

In the case of a CellRanger V2 attribute is present and also the "gene_names" slot is present - so no problems there

**Comment by sjfleming** [comment] 2020-08-06 14:46
Thanks for letting me know, this is helpful.  Are you using Seurat3?

**Comment by GreenGilad** [comment] 2020-08-06 16:19
Yes. Using Seurat 3.2 (which I have just updated too from 3.1 recently)
I did compare the code of the Read10x_h5 function with the previous version to see that it isn't in the Seurat side

**Comment by sjfleming** [comment] 2020-08-19 22:35
Thanks.  Okay, yes, I will definitely make it a priority to have Seurat input compatibility by the time we release this version officially.

**Comment by megan1111** [comment] 2020-10-20 10:06
Hello! Just checking, were you able to resolve this? Because I'm facing the same issue as well using the CellBender v0.2.0.

**Comment by megan1111** [comment] 2020-10-20 11:24
Just to add, I am using CellRanger v3. Looking into the source code, it seems like having CellRanger v3 will alter the group creation for the output file generation, as compared to v0.1.0 where the group creation is standard regardless of which Cell Ranger version. Thank you so much for  your help on this!

**Comment by sjfleming** [comment] 2020-10-21 17:01
Oh, I see I forgot my promise above!  I will take another look and see if I can figure out a small change that will enable Seurat 3 to automatically read these h5 files.  I admit I do not yet understand exactly what the issue is.

**Comment by qrzhang** [comment] 2020-10-23 19:32
Just to add that I'm also facing the same issue and @GreenGilad 's suggestion doesn't work for me. I'm using 10X V3 and the latest CellBender 0.2. And the following are the errors when I tried to use  GreenGilad's solution. I'm running it on macOS Catalina 10.15.7

```r
> data.data <- Read10X_h5(filename = data.file, use.names = TRUE)
Error in `[[.H5File`(infile, paste0(genome, "/", feature_slot)) : 
  An object with name matrix/gene_names does not exist in this group
> f <- hdf5r::H5File$new(data.file, mode="a")
Error in H5File.open(filename, mode, file_create_pl, file_access_pl) : 
  HDF5-API Errors:
    error #000: ../../src/hdf5-1.12.0/src/H5F.c in H5Fopen(): line 793: unable to open file
        class: HDF5
        major: File accessibility
        minor: Unable to open file

    error #001: ../../src/hdf5-1.12.0/src/H5VLcallback.c in H5VL_file_open(): line 3500: open failed
        class: HDF5
        major: Virtual Object Layer
        minor: Can't open object

    error #002: ../../src/hdf5-1.12.0/src/H5VLcallback.c in H5VL__file_open(): line 3465: open failed
        class: HDF5
        major: Virtual Object Layer
        minor: Can't open object

    error #003: ../../src/hdf5-1.12.0/src/H5VLnative_file.c in H5VL__native_file_open(): line 100: unable to open file
        class: HDF5
        major: File accessibility
        minor: Unable to open file

    error #004: ../../src/hdf5-1.12.0/src/H5Fint.c in H5F_open(): line 1590: file is already open for read-only
        class: HDF5
        major: File accessibility
        minor: Unable to open fil
```

Besides, I have also tried to load the same date by scanpy. I also meet an error. I notice another issue is talking about it, I'll update details about my error to #57

**Comment by sjfleming** [comment] 2020-10-27 16:39
`scanpy` loading has (hopefully) been addressed in a satisfactory way in #57 

I will continue to look into `Seurat` loading

**Comment by sjfleming** [comment] 2020-10-27 22:22
Okay, so the `if` statement that @GreenGilad mentioned above is indeed the problem.  Since we create a file using PyTables, there will be a `PYTABLES_FORMAT_VERSION` attribute.

My proposal is to substitute their current `if` statement
https://github.com/satijalab/seurat/blob/fe93b05745e55ec2f66e3f0b4c4196aad9f4d5a7/R/preprocessing.R#L1155

with
```R
if (hdf5r::existsGroup(infile, 'matrix'))
```

For now, I think the code below is a potential workaround.  I may try to submit a pull request to Seurat to incorporate this, as I think it makes more sense than relying on a version attribute from PyTables.

```R
library(Matrix)

ReadCB_h5 <- function(filename, use.names = TRUE, unique.features = TRUE) {
  if (!requireNamespace('hdf5r', quietly = TRUE)) {
    stop("Please install hdf5r to read HDF5 files")
  }
  if (!file.exists(filename)) {
    stop("File not found")
  }
  infile <- hdf5r::H5File$new(filename = filename, mode = 'r')
  genomes <- names(x = infile)
  output <- list()
  if (hdf5r::existsGroup(infile, 'matrix')) {
    # cellranger version 3
    message('CellRanger version 3+ format H5')
    if (use.names) {
      feature_slot <- 'features/name'
    } else {
      feature_slot <- 'features/id'
    }
  } else {
    message('CellRanger version 2 format H5')
    if (use.names) {
      feature_slot <- 'gene_names'
    } else {
      feature_slot <- 'genes'
    }
  }
  for (genome in genomes) {
    counts <- infile[[paste0(genome, '/data')]]
    indices <- infile[[paste0(genome, '/indices')]]
    indptr <- infile[[paste0(genome, '/indptr')]]
    shp <- infile[[paste0(genome, '/shape')]]
    features <- infile[[paste0(genome, '/', feature_slot)]][]
    barcodes <- infile[[paste0(genome, '/barcodes')]]
    sparse.mat <- sparseMatrix(
      i = indices[] + 1,
      p = indptr[],
      x = as.numeric(x = counts[]),
      dims = shp[],
      giveCsparse = FALSE
    )
    if (unique.features) {
      features <- make.unique(names = features)
    }
    rownames(x = sparse.mat) <- features
    colnames(x = sparse.mat) <- barcodes[]
    sparse.mat <- as(object = sparse.mat, Class = 'dgCMatrix')
    # Split v3 multimodal
    if (infile$exists(name = paste0(genome, '/features'))) {
      types <- infile[[paste0(genome, '/features/feature_type')]][]
      types.unique <- unique(x = types)
      if (length(x = types.unique) > 1) {
        message("Genome ", genome, " has multiple modalities, returning a list of matrices for this genome")
        sparse.mat <- sapply(
          X = types.unique,
          FUN = function(x) {
            return(sparse.mat[which(x = types == x), ])
          },
          simplify = FALSE,
          USE.NAMES = TRUE
        )
      }
    }
    output[[genome]] <- sparse.mat
  }
  infile$close_all()
  if (length(x = output) == 1) {
    return(output[[genome]])
  } else{
    return(output)
  }
}
```

Loading a CellBender `remove-background` output file in a legacy CellRanger v2 format:

![image](https://user-images.githubusercontent.com/10214815/97367768-16a93300-1880-11eb-9339-c97131d3ab28.png)


Loading a CellBender `remove-background` output file in the newer CellRanger v3+ format:
(I had to subset to "Gene Expression" to successfully use `CreateSeuratObject`)

![image](https://user-images.githubusercontent.com/10214815/97368412-40af2500-1881-11eb-94e8-b090a2487ffa.png)

**Comment by sjfleming** [comment] 2020-10-27 22:33
https://github.com/satijalab/seurat/issues/3653

**Comment by Ni-Ar** [comment] 2021-03-08 14:27
I'm not sure if my issue is related but I'm mostly interested in understanding the issue here.
For example of I try to read in [this 'all_timepoints_subsampled.h5'](https://zenodo.org/record/4333872) file into R I get this error:

```
DA <- Read10X_h5(filename = subset_h5_path,
                   use.names = F,
                   unique.features = TRUE)

Error in `[[.H5File`(infile, paste0(genome, "/shape")) : 
  An object with name X/shape does not exist in this group

```
and I tried all the above mentioned solutions but none seems to work. 

If I understood correctly the problem is caused by the fact that the`h5` file was generated with Cell Ranger software (version 2.1.0) and aligned to the GRCh37/hg19, but this file format is deprecated and not supported anymore by `Seurat` and this is why I get the error message, right?

I'm running `Seurat` v3.3.3 on R v3.6.2.

Thanks for any elucidation.

**Comment by sjfleming** [comment] 2021-05-03 17:54
@Ni-Ar yes I think you are probably right about that

**Closed by sjfleming** 2021-05-03 17:54 UTC
Labels: bug
