### ISSUE TITLE
Reducing the learning rate and unexpected number of cells

### ISSUE THREAD

**Issue by mihem** [broadinstitute/CellBender#276] opened 2023-09-08 08:48 UTC
@sjfleming  Thanks for this great tool, which is the best solution I know for background removal.
v0.3 is leagues better than v0.2, i especially enjoy the extensive QC, the automatic QC analysis, the faster running time and the fact that you don't ahve to specify the number of epected cells and total droplets anymore, and that it work's much better on difficult samples.

We've run cellbender on ~25 samples and I am quite happy with the results. However, I often had to re-run cellbender with a lower learning rate (in several cases even three rounds with hal of the learning rate for each round). I saw that this effected the results quite dramatically:

Default learning rate:
![image](https://github.com/broadinstitute/CellBender/assets/46907494/7853ae1f-ede6-4a11-ad65-c8a53625db08)

resulting in 30 481 found cells
![image](https://github.com/broadinstitute/CellBender/assets/46907494/964d4e2f-5010-461a-a624-022f86996c20)

and after two rounds of reducing the learning rate by factor 2 (so learning rate 0.000025) this learning curve looked much better and the automatic QC analysis was happy:

![image](https://github.com/broadinstitute/CellBender/assets/46907494/771c531f-2150-42a7-9218-ca97682894d9)

resulting in only 17 539 found cells!

![image](https://github.com/broadinstitute/CellBender/assets/46907494/acb8021a-ef83-46a2-ba54-c436f645613f)

This is also closer to what Cellranger estimates:

![image](https://github.com/broadinstitute/CellBender/assets/46907494/db1a1ca9-1710-40d8-9316-00ac1b7946df)

So my questions here:
Q1: Do you also think that the last run resulting in 17 539 cells is the best one and the first run with the higher learning was massively overestimating the number of cells? With cellbender v0.2 I often found that cel numbers were much higher than what cellranger expected, but based on your FAQ  https://cellbender.readthedocs.io/en/latest/troubleshooting/index.html#a11 I thought that cellranger was actually underestimating  the cell number.
Q2: In approximately 50% of the samples to reduce the learning rate by factor 2, and and several of them even a second time. If you have many samples, this can be time consuming. Is there a faster way to find the right learning rate? Is there something wrong with using 0.00025 as the default learning rate?

In one sample the training curve looked okay

![image](https://github.com/broadinstitute/CellBender/assets/46907494/4f3a4168-21c5-440b-8e0d-812a3991db8c)

but the resulting 61 959 cells:

![image](https://github.com/broadinstitute/CellBender/assets/46907494/cf3c5747-d5a8-4a06-95e9-8572eb5c08ae)

were much higher than what would be expected based on cellranger:

![image](https://github.com/broadinstitute/CellBender/assets/46907494/a735311c-4a41-4492-abb4-722badfbd174)

Q3: What's your opinion here?

And in one sample I could not get a reasonable learning curve although we did 6 rounds of reducing the learning rate. 
Default learning rate:

![image](https://github.com/broadinstitute/CellBender/assets/46907494/04680d25-6e15-40c1-ae81-0a5cf5f3925a)

resulting in 16 044 cells:
![image](https://github.com/broadinstitute/CellBender/assets/46907494/00c94a52-573a-4158-8f3d-d2fdbe27c037)

1/64 of the default learning rate, so 0.0000015625 looks much better I think, but automatic QC still not happy

![image](https://github.com/broadinstitute/CellBender/assets/46907494/38ffb219-d147-4d61-a059-216e16736912)

resultg in 9662 cells only:

![image](https://github.com/broadinstitute/CellBender/assets/46907494/c33c18ca-5e72-4999-b5a7-b3bdb7013b6c)

Based on cellranger the expected number of cells is much higher, 35 646. The UMI plot does not look great I agree, but the quantiative QC measure are all good (high fraction of reads mapped anti-sense to genes expected in nuclei https://kb.10xgenomics.com/hc/en-us/articles/360000087552-Why-do-I-have-a-high-percentage-of-reads-mapping-to-intronic-regions-)

![image](https://github.com/broadinstitute/CellBender/assets/46907494/b594029c-3294-489c-90f4-9ff1e1f38b7b)

Q4: Would you recommend to reduce the learning rate even further? Why is the cell count so much lower than in Cellranger?

Happy to share any data.

Sorry for the long post.

**Comment by sjfleming** [comment] 2023-09-08 17:32
Thanks for your questions @mihem , and glad cellbender has been useful for you!

Overall, I think you are bringing up an important point: it seems like my default learning rate is probably too high in v0.3.0.  Some samples do fine, but you're right: there's really no point in setting a high learning rate and having do re-run a bunch of samples, especially when the samples that converge with a learning rate of 1e-4 in 150 epochs also seem to converge just fine with a learning rate of 1e-5 (or 5e-5) in 150 epochs.  I will do a bit more testing in this area, and then I think I might just lower the default learning rate.

Q1: 
Your diagnosis and solution is something I agree with completely: that initial learning curve indicated that cellbender fell into some kind of bad local minimum (one where nearly "everything is a cell") and did not find the optimal solution.  This can be caused by a learning rate that's too high, so reducing the learning rate was exactly the right thing to do.  The re-run with 17k cells looks fantastic to me.  Now... as for why 17k is less than the 19k that cellranger said... I cannot quite be sure.  Typically I do see cellbender call more cells than cellranger.  Almost always.  I would love to say "cellbender is right!" but if it were me analyzing my own dataset, I would look at those droplets which were called cells by cellranger (and not by cellbender) and see what you think they are.  If they look like real cells, I would try to get cellbender to keep them.  Now, this is not 100% straightforward, since cellbender only gives you counts for droplets it thinks contain cells (empty drops have zero counts in the output). So, if you were really convinced cellbender is missing something real, you could try to play with the `--force-cell-umi-prior` input argument.  Maybe you could try `--force-cell-umi-prior 500` in your case.  This can help force cellbender to recognize more of those lower-count droplets as cells.  
(Ideally though, when you look at the run you already did, and look at the extra droplets that cellranger retains, you might see they actually look like they have the same gene expression profile as the empty droplets, and don't look like real cells.)

Q2:
There is absolutely nothing wrong with using 2e-5 (or some other value) as the learning rate for all your samples (and as I said above, I might make this the default in the future).  The only thing to be careful of is that if you go too low, the learning curve at 150 epochs will start to look like it has not yet converged.  Maybe the cell probabilities will also not look converged (i.e. there will be a ton of droplets with probabilities between 0.25 and 0.75).  You do want to choose a combination of learning rate and epochs that gives you a learning curve that looks like it has (nearly) converged to some value, so that you can be confident cellbender's solution would not keep changing if you kept training longer.

Q3:
Here I believe the automated heuristics used to estimate cells and empties has gone wrong.  CellBender thinks that the empties are way out past droplet 60k.  I do not agree, based on the CellRanger UMI curve.  The empty droplets in this experiment are around droplet 20k - 60k.  You can make cellbender find the right priors on this sample by including `--low-count-threshold 100` as an input argument.  (This tells cellbender to totally ignore droplets with < 100 UMI counts, which would be appropriate here.) It should then be able to estimate the priors appropriately.

Q4:
Now this experiment looks like a tricky case.  I do think that cellbender's automated heuristics are (potentially) not including enough droplets in the analysis here...  Eyeballing the UMI curve plotted by CellRanger, I can see that there are two possible scenarios:
1. Your second result with the low learning rate is basically right, and there are like 10k cells in this dataset.
2. The empty droplets are really between like 70k-100k (I can't see exactly without being able to zoom in) on the UMI curve, and CellRanger is actually underestimating cells by quite a lot.  CellBender is also totally missing out on them because it only included 16k droplets.

Resolving which of these two scenarios is more plausible might take a bit of digging.  Firstly, if you look at the droplets from 35k - 50k, do they actually look empty?  Do they look like the droplets out near 100k (the ones with like 300 UMI counts)?  If the experiment was conducted the same way as the others, then the others contain somewhere in the ballpark of several hundred counts in empty droplets.  Scenario (1) would indicate that this experiment has several thousand counts in empty droplets, which would be quite different.  Scenario (2) would be more in line with the ambient RNA level in the other samples.  But... scenario (2) would also mean there are like 50k cells in this experiment.  Is that possible?  Looks like your other experiments did not target that many cells.

If you end up thinking that scenario (2) might be a possibility, I would re-run CellBender with `--expected-cells 35000 --total-droplets-included 60000` (where that 60000 number is a complete guess... try to look at the UMI curve and include some of those empty droplets with ~300 UMI counts.

**Comment by mihem** [comment] 2023-09-14 08:15
@sjfleming  Thanks so much for your quick and very extensive response.

It took me some days to do these analysis.

Learning rate: Agree. At least in my samples 1/2 or 1/4 of the current default would be better.

Concerning the first example in Q1.
I analyzed cellranger vs cellbender version, using default Seurat cutoff (nFeature_count > 200), plus a sample-based cutoff, did not reduce the number of cells substantially, because they looked pretty similar in the Seurat QC plots (except maybe two with high MT filtered out by bender)
![image](https://github.com/broadinstitute/CellBender/assets/46907494/edc3eea2-71fd-49f9-ad80-573374976722)
![image](https://github.com/broadinstitute/CellBender/assets/46907494/f60c3710-3763-4f6a-a9e7-88eafe65f68a)

In the UMAP both clustered really nice, however, cluster10 aand also cluster 3 were basically removed by cellbender.
![image](https://github.com/broadinstitute/CellBender/assets/46907494/b953985e-dd1d-43bf-ad4d-d12e715fa7e2)

But these were mostly expressing low quality transcripts:

![image](https://github.com/broadinstitute/CellBender/assets/46907494/5337f795-1735-4153-ba0c-32f91fd22b27)

top markes of cluster 10:
![image](https://github.com/broadinstitute/CellBender/assets/46907494/2eec7519-35c8-4580-b17c-ad4fc4d96ae8)

-> so I think cellbender version is much better here :+1: 

Q3: I think this is dangerous. If i look at the automated QC results, everything looks fine, and actually everything looked fine to me ..except that the cell numbers was that high.
Thanks for the suggestion, we will try that!

**Can you think of a way of telling the users automatically that the heuristics hvae gone wrong? Or if that's not possible how do I know that there's a problem here?**

I have another sample, which looks pretty similar:

![image](https://github.com/broadinstitute/CellBender/assets/46907494/33a09966-ed09-4219-9612-d4bb9a5dc19d)

![image](https://github.com/broadinstitute/CellBender/assets/46907494/6bd21634-fef8-4867-8dc2-f26f2d1907c2)


But here the number of cells is comparable to Cellranger: cellbender: 31357 cellranger: 35142

![image](https://github.com/broadinstitute/CellBender/assets/46907494/ceec5f2b-facd-4c0f-a32b-75d2307f1937)


zoom in:
![image](https://github.com/broadinstitute/CellBender/assets/46907494/750a289f-89ca-485d-a8c4-5beece736303)

Actually I would have though that the cell number is lower (input nuclei were 15 000 intact nuclei), but based on the UMI it's not totally of, or what do you think?

Q4: 
Yes, this is a tricky one. So these are all frozen nerves, processed by single nuclei sequencing. This one is an older sample so could be higher ambient RNA level (this is what you mean right?). Input number was again 15 000 intact nuclei. Sometimes this is quite far off the output number of nuclei, so I would think 5k-30k is not completely unrealistic, but >50k would be really strange I think.

I analyzed cellranger, cellbender, and the cells that were present in ranger but not bender.
Again Seurat filtering did not change the results much (before is already filtered by min.features = 200 and min.cells = 3; after is after removing ones with high MT and high nFeatures)
![image](https://github.com/broadinstitute/CellBender/assets/46907494/b471a2f1-33b6-44db-b1c3-87af05b4aa87)

UMAP does not give such a clear result as in the previous example:

![image](https://github.com/broadinstitute/CellBender/assets/46907494/b6492626-30fb-47f6-a9af-fd7d21f4afb0)

Maybe bender removed some actual cells?
![image](https://github.com/broadinstitute/CellBender/assets/46907494/736a869e-1214-49bf-bd37-0b4a8cbbe080)

But mostly bender looks much cleaner:
![image](https://github.com/broadinstitute/CellBender/assets/46907494/3c139499-5ce3-41d4-8e5d-50c8b5df8f75)


-> so in this example i find it more difficult to say, but I still prefer the clean cellbender output, even if a few potential correct cells got filtered out. What do you think?

Thank you!

**Comment by mihem** [comment] 2023-09-16 09:50
@sjfleming 

We re-ran the sample of Q3 now with `--low-count-threshold 100` as you advised.
With a learning rate of `0.00005`:

![image](https://github.com/broadinstitute/CellBender/assets/46907494/d6bc6ac2-7f0e-4f3e-b7b6-051660029e52)

20825 cells, so much closer to what you would expect based on cellranger:

![image](https://github.com/broadinstitute/CellBender/assets/46907494/045c942d-ef23-4485-ad7b-8ece1ba53630)


However, learning rate no optimally, so reducing it to `0.000025`, learning curve looks good I thik:
![image](https://github.com/broadinstitute/CellBender/assets/46907494/0c808b25-269f-452a-81c5-5c90cd8b93c4)

cells now only 16 487

![image](https://github.com/broadinstitute/CellBender/assets/46907494/44f58428-9312-46a6-b2f0-9891a3592009)

and reducing the learning rate even further to `0.000125`, learning curve still looks fine to me:

![image](https://github.com/broadinstitute/CellBender/assets/46907494/4f8416e0-b054-4e19-9f5b-3804fc7e0e11)


cell numbers even lower: 15 811, but probablities look better to me

![image](https://github.com/broadinstitute/CellBender/assets/46907494/bd43ad56-bb75-46c6-80d5-664515d1f927)

-> So i would say last one is the best one. What's you opinion on that?


In general, my key takeaways would be: default learning rate should be lower, and in a few samples with abnomrally high cell counts, parameters need to be set manually (would be great if their was a warning in the automatic QC report).

Thanks again for this great package, really makes a difference for difficult samples with high background I think.

**Comment by mihem** [comment] 2023-09-22 12:52
@sjfleming  Sorry, could you maybe have a look at my last two messages, when you find time?

Also in the meantime we ran another ~20 sampls with cellbender on the same material.

In three cellbender resulted in much too many cells:

![image](https://github.com/broadinstitute/CellBender/assets/46907494/f0728203-ef1b-4f4e-9e41-3066c271ed48)


cellranger zoom

![image](https://github.com/broadinstitute/CellBender/assets/46907494/0ea233ff-48b8-46d6-965c-50b5f0b90f72)

Learning rate looks good:

![image](https://github.com/broadinstitute/CellBender/assets/46907494/ee51ac2e-9fde-4e7f-8039-7996116ec574)


But cell counts much too high:

![image](https://github.com/broadinstitute/CellBender/assets/46907494/98cdab78-d4c0-4cc0-aa9f-a54b8739c3a5)

-> so would you recommend running cellbender with `--low-count-threshold 100` again?

And then again1-2 samples, where the clel propbablities look equally strange, but the number looks plausible based on cellranger

![image](https://github.com/broadinstitute/CellBender/assets/46907494/a68f3883-3a4d-45ce-bc5e-e78c2e0389e6)

![image](https://github.com/broadinstitute/CellBender/assets/46907494/133e28b1-7a7e-41c7-b47f-faebedf2ac5d)

![image](https://github.com/broadinstitute/CellBender/assets/46907494/200a95fc-23e9-48a3-9c79-cb1689cc0585)


![image](https://github.com/broadinstitute/CellBender/assets/46907494/5e9b4a7a-9203-4be9-8fca-8655e1e5a318)

-> would you think that this is correct or also run it with  `--low-count-threshold 100`  or some other setting?

Thank you !!

**Comment by sjfleming** [comment] 2023-09-22 19:38
> Can you think of a way of telling the users automatically that the heuristics hvae gone wrong? Or if that's not possible how do I know that there's a problem here?

Good questions.  I haven't yet thought of a good way to automatically tell if those heuristics are wrong.  You sort of have to know something about the experiment... i.e. is 65k cells just way too much?  One thing you might be able to look at (but it's not super clear) is that the fraction of `--total-droplets-included` that was said to be a "cell" is quite high, close to 1.  When CellBender says "everything is a cell!", that's basically never good.  But it's also not crystal clear, because in some of your examples, it's not finding _everything_ to be a cell.

There is a metric included in the output `metrics.csv` which captures the fraction of total droplets included which were called cells.

The heuristics for determining `--total-droplets-included` also include a safeguard that it never goes beyond 70k:
https://github.com/broadinstitute/CellBender/blob/4990df713f296256577c92cab3314daeeca0f3d7/cellbender/remove_background/consts.py#L114C35
but for your dataset, this value was too large to be helpful.

Open to other suggestions though!

-------------
For this sample,
<img width="676" alt="image" src="https://github.com/broadinstitute/CellBender/assets/10214815/159296d1-3cb7-4198-b3a8-a9e4efdac348">

I think that the total number of droplets included is too low.  Looking at the CellRanger UMI curve, I am not convinced that all the droplets beyond 30k are "surely empty".  If this was what the CellBender defaults gave you, I think this is a case where the defaults did not work perfectly.  I would use `--expected-cells 20000 --total-droplets-included 50000`.  I think this is basically CellBender trying to tell us "there are more cells further down the UMI curve".

---------------
Q4
> so in this example i find it more difficult to say, but I still prefer the clean cellbender output, even if a few potential correct cells got filtered out. What do you think?

I tend to agree with you, but it's a bit of a judgement call. The UMAP makes it look like this whole sample is potentially just lower quality than the other samples.  It's possible that being older, there was more nuclei rupture, leading to more ambient RNA.  This may be contributing to the "blob"-like shape of the UMAP.  (If you redo the UMAP with the CellBender cells, then you may see a cleaner UMAP.  It looks from the picture like you created a UMAP using all cells, and then just showed the CellBender cells in the middle panel.  But re-computing the UMAP with CellBender cells only might make it look a bit more tidy.  I'd be tempted to believe the lower cell count from CellBender for this sample.)

**Comment by sjfleming** [comment] 2023-09-22 20:29
Q3 learning rate retry:
> So i would say last one is the best one. What's you opinion on that?

I agree.  I think the last or second last one looks great.  Probably the last one.

> In general, my key takeaways would be: default learning rate should be lower, and in a few samples with abnomrally high cell counts, parameters need to be set manually (would be great if their was a warning in the automatic QC report).

I agree with both of these points!

-------------
This sample
<img width="676" alt="image" src="https://github.com/broadinstitute/CellBender/assets/10214815/dafa6a96-a285-4bef-a792-a6972c4858da">

should be fixed by using `--low-count-threshold 100`

------------------

This one
<img width="449" alt="image" src="https://github.com/broadinstitute/CellBender/assets/10214815/2f7367df-9fc6-47ea-956c-987ec8b605c6">

I think is another case where the cellbender automated heuristics have underestimated `--total-droplets-included` sadly.
<img width="667" alt="image" src="https://github.com/broadinstitute/CellBender/assets/10214815/0f3529a5-168b-44fc-8b77-cf04431f1652">

CellBender again thinks everything is a cell, and that's because we need to give it more droplets.  Maybe try `--expected-cells 15000 --total-droplets-included 40000`

**Comment by mihem** [comment] 2023-09-22 20:55
Thank you.

Regarding heuristics if cell number is too high. Not qualified enough to think of an automatic QC way. Automatic would be super nice, but maybe at least tell the user in the html file to check if the number of cells is plausible or so.

Thanks also for your suggestions.

Maybe one last question for the last plot (and the responding plot before):  do you think the resulting number of cells is than 15 000 (so expected number of cells)? Because I had a similar problem in the Cellranger v0.2 (that nearly all cells in the plot had a high cell probability) but increasing the number of droplets led to a high number of cells.
But as in the examples above I think that there are probably around 15 000 cells.

And what happens if we also use 
--low-count-threshold 100 here?

**Comment by mihem** [comment] 2023-09-23 15:09
@sjfleming Ah okay, I thought about it again, and I think now I understand better.
The problem in these very high unplausible samples was that the priors were much too low (e.g. in my log empty droplet prior count 29, cell prior count 705), which then increased to reasonable estimates by using `--low-count-threshold 100 here?`
But in the last samples the priors are actually plausible (checked them in the logs), only total-droplets included is a little low. However, i think the cellnumber is a little high und I would like to force it to be lower, so in this sample:
![image](https://github.com/broadinstitute/CellBender/assets/46907494/81d530f7-3ac6-401c-9b89-c11c2a309ed9)



![image](https://github.com/broadinstitute/CellBender/assets/46907494/7a842097-4e46-41fa-a075-8ea886f96557)

I would like to get like 10 000 - 15 000 cells, not 25 000.
Can I acheive that by using `--expected-cells 10000 --total-droplets-included 40000` or can i  force this even more by using 
--force-cell-umi-prior? I would use `--force-cell-umi-prior 2000` but actually prior umi is already at 1950 in the logs, so I am suprised that this results in ~25 000 cells and not ~10 000 cells?

Thanks you
`

**Comment by mihem** [comment] 2023-09-27 11:59
We tried differences settings and as you said, including `--expected-cells` and `total-droplets-included` in combination with a low learning rate leads to much better results in difficult samples.

default parameters:

![image](https://github.com/broadinstitute/CellBender/assets/46907494/9fe20f6c-5912-4e1e-8b12-e41e5f630778)

![image](https://github.com/broadinstitute/CellBender/assets/46907494/d8c3f774-bbd5-4452-9d6b-90cfc1902cdc)

after several rounds of reducing the learning rate
` --learning-rate 0.000003125`
still not great:

![image](https://github.com/broadinstitute/CellBender/assets/46907494/99d7c35c-6ea1-4a5f-8a3e-76a00fae1b75)

![image](https://github.com/broadinstitute/CellBender/assets/46907494/deda9779-7fb1-46e6-af74-23f58ffa5ab1)

including expected cells and total droplets:

`--learning-rate 0.000003125 --expected-cells 10000 --total-droplets-included 50000`
looks much better I think:

![image](https://github.com/broadinstitute/CellBender/assets/46907494/7b12fd1b-dddb-4825-a5c6-7b83618f7c14)

![image](https://github.com/broadinstitute/CellBender/assets/46907494/63d6eb84-dbb9-45ba-a41c-303967437233)


@sjfleming  not sure you want to comment on this, or include some of this stuff into the general docs .. otherwise feel free to close. 
Thanks for the great guidance.

**Comment by sjfleming** [comment] 2023-10-03 04:13
Yeah that last sample was a real tricky one!  I tend to agree with you that the last plot you show looks the best... I think around 20k cells is probably the most reasonable outcome.

And I would still recommend (as I always do): try to do further cell QC after CellBender.  While CellBender will identify the "non-empty" droplets, this doesn't necessarily mean they're all high quality cells that would be great to use in downstream analyses.

Glad you were able to get things working in a satisfactory way!

**Closed** 2023-10-03 05:10 UTC
Labels: user question

**Comment by EstherMY** [comment] 2025-09-09 23:51
Dear developer @sjfleming,
Thank you very much for developing CellBender. I have recently started using the tool for the removal of ambient RNA from human single-nucleus sequencing samples. I carefully read issues 220, 276, 294, and 283, and configured the parameters --learning-rate 0.00005 and 0.000025, --expected-cells 7000, and --fpr 0.01 for sample S5, which is still not producing satisfactory outcomes.
Another point is that I have several samples, and about half of them seem to perform better with the first learning rate, while the other half with the second. From what I understand, it seems more advisable to use the same --learning-rate across all samples, and since I have not been able to achieve this, I would like to seek your professional opinion. Would you recommend a more suitable configuration or parameter adjustment?
Overall, my results appear to be most similar to those described in issues 276 and 294. 

[Amostra N1_ –learning-rate 0.pdf](https://github.com/user-attachments/files/22244781/Amostra.N1_.learning-rate.0.pdf)
